apiVersion: v1
kind: Service
metadata:
  name: rrt-project-service
spec:
  selector:
    app: rrt-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  # Match this with the port exposed in your Docker container
  type: NodePort  # Exposes the service externally via a port on the host machine

